db.password=12345
mail.username=lyhourhoun496@gmail.com
mail.password=ovnp ilqa qbiz csdi
stripe.api.key=ROTATED_REMOVEDgit
stripe.publishable.key=pk_test_51To2bq36K9AaNhTya64OJsTOikS00MalN7pkYJwlBVI2I7VgJYhrK6RUybgWmgVib51mCIklvH1GXBn8uJ0pSSBq001OzssPO6